security:
    encoders:
      App\Entity\User:
        algorithm: bcrypt
    providers:
        user_provider:
            entity:
              class: App\Entity\User
        api_key_user_provider:
            id: App\Security\ApiKeyUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        user_main:
            anonymous: ~
            provider: user_provider
            stateless: true
            form_login:
                login_path: security_login
                check_path: security_login
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
        api_main:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: App\Security\ApiKeyAuthenticator
            provider: api_key_user_provider
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_API }

